{
  "crate_name": {
    "text": "greetings"
  },
  "crate_path": "idl-tests/greetings.rs",
  "definitions": [
    [
      {
        "names": [
          {
            "text": "greetings"
          },
          {
            "text": "Greetings"
          }
        ]
      },
      {
        "Resource": {
          "span": {
            "path": "idl-tests/greetings.rs",
            "start": {
              "byte": 11,
              "line": 1,
              "column": 12
            },
            "end": {
              "byte": 20,
              "line": 1,
              "column": 21
            }
          },
          "name": {
            "text": "Greetings"
          },
          "methods": [
            {
              "span": {
                "path": "idl-tests/greetings.rs",
                "start": {
                  "byte": 76,
                  "line": 6,
                  "column": 12
                },
                "end": {
                  "byte": 79,
                  "line": 6,
                  "column": 15
                }
              },
              "category": "Constructor",
              "name": {
                "text": "new"
              },
              "signature": {
                "is_async": "No",
                "inputs": [],
                "output_ty": {
                  "main_ty": {
                    "span": {
                      "path": "idl-tests/greetings.rs",
                      "start": {
                        "byte": 11,
                        "line": 1,
                        "column": 12
                      },
                      "end": {
                        "byte": 20,
                        "line": 1,
                        "column": 21
                      }
                    },
                    "kind": {
                      "UserType": {
                        "qname": {
                          "names": [
                            {
                              "text": "greetings"
                            },
                            {
                              "text": "Greetings"
                            }
                          ]
                        }
                      }
                    }
                  },
                  "error_ty": null
                }
              }
            },
            {
              "span": {
                "path": "idl-tests/greetings.rs",
                "start": {
                  "byte": 175,
                  "line": 12,
                  "column": 12
                },
                "end": {
                  "byte": 183,
                  "line": 12,
                  "column": 20
                }
              },
              "category": {
                "BuilderMethod": "ByValue"
              },
              "name": {
                "text": "language"
              },
              "signature": {
                "is_async": "No",
                "inputs": [
                  {
                    "span": {
                      "path": "idl-tests/greetings.rs",
                      "start": {
                        "byte": 194,
                        "line": 12,
                        "column": 31
                      },
                      "end": {
                        "byte": 202,
                        "line": 12,
                        "column": 39
                      }
                    },
                    "name": {
                      "text": "language"
                    },
                    "refd_ty": {
                      "Ref": [
                        "AnonRef",
                        {
                          "span": {
                            "path": "idl-tests/greetings.rs",
                            "start": {
                              "byte": 205,
                              "line": 12,
                              "column": 42
                            },
                            "end": {
                              "byte": 208,
                              "line": 12,
                              "column": 45
                            }
                          },
                          "kind": {
                            "String": {
                              "repr": "StrRef"
                            }
                          }
                        }
                      ]
                    }
                  }
                ],
                "output_ty": {
                  "main_ty": {
                    "span": {
                      "path": "idl-tests/greetings.rs",
                      "start": {
                        "byte": 11,
                        "line": 1,
                        "column": 12
                      },
                      "end": {
                        "byte": 20,
                        "line": 1,
                        "column": 21
                      }
                    },
                    "kind": {
                      "UserType": {
                        "qname": {
                          "names": [
                            {
                              "text": "greetings"
                            },
                            {
                              "text": "Greetings"
                            }
                          ]
                        }
                      }
                    }
                  },
                  "error_ty": null
                }
              }
            },
            {
              "span": {
                "path": "idl-tests/greetings.rs",
                "start": {
                  "byte": 297,
                  "line": 17,
                  "column": 12
                },
                "end": {
                  "byte": 302,
                  "line": 17,
                  "column": 17
                }
              },
              "category": {
                "InstanceMethod": "ByValue"
              },
              "name": {
                "text": "greet"
              },
              "signature": {
                "is_async": "No",
                "inputs": [
                  {
                    "span": {
                      "path": "idl-tests/greetings.rs",
                      "start": {
                        "byte": 309,
                        "line": 17,
                        "column": 24
                      },
                      "end": {
                        "byte": 313,
                        "line": 17,
                        "column": 28
                      }
                    },
                    "name": {
                      "text": "name"
                    },
                    "refd_ty": {
                      "Owned": {
                        "span": {
                          "path": "idl-tests/greetings.rs",
                          "start": {
                            "byte": 315,
                            "line": 17,
                            "column": 30
                          },
                          "end": {
                            "byte": 321,
                            "line": 17,
                            "column": 36
                          }
                        },
                        "kind": {
                          "String": {
                            "repr": "String"
                          }
                        }
                      }
                    }
                  }
                ],
                "output_ty": {
                  "main_ty": {
                    "span": {
                      "path": "idl-tests/greetings.rs",
                      "start": {
                        "byte": 341,
                        "line": 17,
                        "column": 56
                      },
                      "end": {
                        "byte": 347,
                        "line": 17,
                        "column": 62
                      }
                    },
                    "kind": {
                      "String": {
                        "repr": "String"
                      }
                    }
                  },
                  "error_ty": {
                    "span": {
                      "path": "idl-tests/greetings.rs",
                      "start": {
                        "byte": 326,
                        "line": 17,
                        "column": 41
                      },
                      "end": {
                        "byte": 348,
                        "line": 17,
                        "column": 63
                      }
                    },
                    "kind": {
                      "Error": {
                        "repr": "AnyhowError"
                      }
                    }
                  }
                }
              }
            }
          ]
        }
      }
    ]
  ]
}