{
  "crate_name": {
    "text": "hello_world"
  },
  "crate_path": "idl-tests/hello_world.rs",
  "definitions": [
    [
      {
        "names": [
          {
            "text": "hello_world"
          },
          {
            "text": "hello_world"
          }
        ]
      },
      {
        "Function": {
          "span": {
            "path": "idl-tests/hello_world.rs",
            "start": {
              "byte": 7,
              "line": 1,
              "column": 8
            },
            "end": {
              "byte": 18,
              "line": 1,
              "column": 19
            }
          },
          "name": {
            "text": "hello_world"
          },
          "signature": {
            "is_async": "No",
            "inputs": [],
            "output_ty": {
              "main_ty": {
                "Owned": [
                  "Owned",
                  {
                    "span": {
                      "path": "idl-tests/hello_world.rs",
                      "start": {
                        "byte": 24,
                        "line": 1,
                        "column": 25
                      },
                      "end": {
                        "byte": 30,
                        "line": 1,
                        "column": 31
                      }
                    },
                    "kind": {
                      "String": {
                        "repr": "String"
                      }
                    }
                  }
                ]
              },
              "error_ty": null
            }
          }
        }
      }
    ]
  ]
}