{
  "crate_name": {
    "text": "hello_world"
  },
  "definitions": [
    [
      {
        "names": [
          {
            "text": "hello_world"
          },
          {
            "text": "hello_world"
          }
        ]
      },
      {
        "Function": {
          "span": {
            "path": "test/idl/hello_world.rs",
            "start": {
              "byte": 7,
              "line": 1,
              "column": 8
            },
            "end": {
              "byte": 18,
              "line": 1,
              "column": 19
            }
          },
          "name": {
            "text": "hello_world"
          },
          "signature": {
            "is_async": "No",
            "inputs": [],
            "output_ty": {
              "main_ty": {
                "kind": "String",
                "rust_repr": {
                  "kind": {
                    "Named": [
                      "String",
                      [],
                      {}
                    ]
                  }
                }
              },
              "error_ty": null
            }
          }
        }
      }
    ]
  ]
}